language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install --dev --prefer-source

script:
  - vendor/bin/phpunit
  - vendor/bin/phpspec run
